name: Deploy to EC2

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore ApiAuth/ApiAuth.csproj

    - name: Build
      run: dotnet build ApiAuth/ApiAuth.csproj --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ApiAuth/ApiAuth.csproj --configuration Release --output ./publish

    - name: Deploy to EC2 via SSH
      uses: appleboy/scp-action@v0.1.7
      with:
        host: 172.20.4.202
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        source: ./publish/
        target: /home/ec2-user/faast-desa/apiauth/prod2

    - name: Restart service on EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: 172.20.4.202
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo systemctl restart DESA-ApiAuth
