name: Build, Test, and Publish

on:
  push:
    branches: 
      - faast/desa
      - faast/stage
      - faast/preProd
      - develop
  pull_request:
    branches: 
      - faast/desa
      - faast/stage
      - faast/preProd
      - develop
  # workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore ApiAuth/ApiAuth.csproj

      - name: Publish
        run: dotnet publish ApiAuth/ApiAuth.csproj -c Release -o bin

      - name: Package build output
        run: |
          mkdir -p packaged
          tar -czvf packaged/package.tar.gz -C bin .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: packaged
          path: packaged/package.tar.gz

  publish-client:
    runs-on: ubuntu-latest
    needs: [build-and-test]
    # if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download packaged artifact
        uses: actions/download-artifact@v4
        with:
          name: packaged
          path: packaged

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git

      - name: Unpack artifact
        run: |
          rm -rf production
          mkdir -p upload
          tar -xf packaged/package.tar.gz -C upload

      - name: Configure git
        run: |
          git config --global user.email "${{ secrets.DEPLOY_EMAIL_AUTH }}"
          git config --global user.name "${{ secrets.DEPLOY_USER_AUTH }}"

      - name: Initialize and push to client repo
        env:
            GH_USER: ${{ secrets.DEPLOY_USER_AUTH }}
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
            REPOSITORY_NAME: ${{ secrets.DEPLOY_REPOSITORY_NAME }}
        run: |
          cd upload
          git init
          URL_REPOSITORY_DEPLOY="https://${GH_USER}:${GH_TOKEN}@github.com/faast-app/${REPOSITORY_NAME}.git"
          git remote add deploy "$URL_REPOSITORY_DEPLOY"
          git ls-remote deploy || { echo "Remote authentication failed"; exit 128; }
          git add .
          VERSION_REPO_CLIENTE=$(cat ../version.txt)
          echo "VERSION_REPO_CLIENTE: $VERSION_REPO_CLIENTE"
          git commit --allow-empty -m "Solicitando Pase ${VERSION_REPO_CLIENTE}"
          git checkout -b "$VERSION_REPO_CLIENTE"
          git push deploy "$VERSION_REPO_CLIENTE"
